
import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import BackgroundEffect from '../components/BackgroundEffect';

const Tool: React.FC = () => {
  return (
    <div className="min-h-screen bg-cyberpunk-dark text-white relative">
      <BackgroundEffect />
      
      <div className="relative z-10">
        <Header />
        <main className="container mx-auto px-4 py-16">
          <div className="glass rounded-xl p-8 max-w-4xl mx-auto">
            <h1 className="text-4xl md:text-5xl font-bold text-gradient mb-8 text-center">
              Snoop Image AI Detector
            </h1>
            
            <div className="space-y-8">
              <div className="text-center">
                <p className="text-xl mb-6">Upload an image to check if it was generated by AI</p>
                <div className="border-2 border-dashed border-white/20 rounded-lg p-12 max-w-lg mx-auto hover:border-neon-purple/50 transition-colors">
                  <div className="flex flex-col items-center">
                    <span className="neon-text-purple text-5xl mb-4">+</span>
                    <p className="text-white/70">Drag & drop your image here or click to browse</p>
                    <p className="text-xs text-white/50 mt-2">Supports JPG, PNG, WEBP (Max 10MB)</p>
                  </div>
                </div>
              </div>
              
              <div className="flex justify-center">
                <button className="px-8 py-3 bg-gradient-to-r from-neon-purple to-neon-blue rounded-lg font-bold text-white hover:shadow-[0_0_20px_rgba(159,21,255,0.5)] transition-all disabled:opacity-50 disabled:cursor-not-allowed">
                  Analyze Image
                </button>
              </div>
              
              <p className="text-center text-sm text-white/60">
                Note: This is a demonstration page. The actual analysis functionality is not implemented in this preview.
              </p>
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default Tool;
