
import React, { useState, useEffect } from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import BackgroundEffect from '../components/BackgroundEffect';
import { ArrowUpFromLine } from 'lucide-react';

const Tool: React.FC = () => {
  const [isDragging, setIsDragging] = useState<boolean>(false);
  
  useEffect(() => {
    // Enhanced SEO for tool page
    document.title = "Free AI Image Detector Tool - Snoop Image AI | AI Web Tools";
    
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', 'Upload and analyze images with our free AI detection tool. Advanced Python-powered analysis determines if images were created by artificial intelligence. Get detailed authenticity scores instantly.');
    }
    
    // Add tool-specific meta keywords
    let metaKeywords = document.querySelector('meta[name="keywords"]');
    if (!metaKeywords) {
      metaKeywords = document.createElement('meta');
      metaKeywords.setAttribute('name', 'keywords');
      document.head.appendChild(metaKeywords);
    }
    metaKeywords.setAttribute('content', 'free ai image detector, upload ai detection, image authenticity tool, ai generated image checker, online ai detector, python image analysis, metadata scanner, pixel analysis tool');
  }, []);
  
  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(true);
  };
  
  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
  };
  
  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    // File upload functionality would be implemented here
  };

  return (
    <div className="min-h-screen bg-cyberpunk-dark text-white relative" itemScope itemType="https://schema.org/WebApplication">
      <BackgroundEffect />
      
      <div className="relative z-10">
        <Header />
        <main className="container mx-auto px-4 py-20 md:py-24">
          <div className="glass rounded-xl p-4 md:p-8 max-w-4xl mx-auto">
            <header>
              <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-gradient mb-6 md:mb-8 text-center" itemProp="name">
                Free AI Image Detector - Snoop Image AI
              </h1>
            </header>
            
            <div className="space-y-6 md:space-y-8" itemProp="description">
              <div className="text-center">
                <p className="text-lg md:text-xl mb-4 md:mb-6">Upload an image to check if it was generated by AI - completely free</p>
                <div 
                  className={`border-2 border-dashed ${isDragging ? 'border-neon-purple' : 'border-white/20'} rounded-lg p-8 md:p-12 max-w-lg mx-auto hover:border-neon-purple/50 transition-colors cursor-pointer`}
                  onDragOver={handleDragOver}
                  onDragLeave={handleDragLeave}
                  onDrop={handleDrop}
                  onClick={() => document.getElementById('file-upload')?.click()}
                  role="button"
                  aria-label="Upload image for AI detection analysis"
                  tabIndex={0}
                >
                  <div className="flex flex-col items-center">
                    <ArrowUpFromLine className="text-neon-purple w-10 h-10 mb-3" aria-hidden="true" />
                    <p className="text-white/70 text-sm md:text-base">Drag & drop your image here or tap to browse</p>
                    <p className="text-xs text-white/50 mt-2">Supports JPG, PNG, WEBP (Max 10MB)</p>
                    <input 
                      type="file" 
                      id="file-upload" 
                      className="hidden" 
                      accept="image/jpeg,image/png,image/webp"
                      aria-label="Select image file for AI detection"
                    />
                  </div>
                </div>
              </div>
              
              <div className="flex justify-center">
                <button 
                  className="px-6 py-2.5 md:px-8 md:py-3 bg-gradient-to-r from-neon-purple to-neon-blue rounded-lg font-bold text-white hover:shadow-[0_0_20px_rgba(159,21,255,0.5)] transition-all disabled:opacity-50 disabled:cursor-not-allowed text-sm md:text-base"
                  aria-label="Analyze uploaded image for AI generation"
                >
                  Analyze Image for Free
                </button>
              </div>
              
              <div className="text-center">
                <h2 className="text-xl font-semibold mb-3 text-neon-blue">Features of Our Free AI Image Detector:</h2>
                <ul className="text-sm md:text-base text-white/80 space-y-1 max-w-2xl mx-auto">
                  <li>• Advanced Python-powered image analysis</li>
                  <li>• Metadata examination and screening</li>
                  <li>• Pixel pattern recognition technology</li>
                  <li>• Deep color distribution analysis</li>
                  <li>• Edge detection and gradient evaluation</li>
                  <li>• Comprehensive authenticity scoring</li>
                </ul>
              </div>
              
              <p className="text-center text-xs md:text-sm text-white/60">
                Note: This is a demonstration page. The actual analysis functionality is not implemented in this preview.
              </p>
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default Tool;
