
import React from 'react';
import { AlertTriangle, Info } from 'lucide-react';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-20 relative overflow-hidden">
      <div className="container px-4 md:px-6 relative z-20">
        <div className="text-center max-w-3xl mx-auto mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            <span className="text-gradient">Legal Disclaimer</span>
          </h2>
          <p className="text-gray-300 text-lg">
            Important information about using Snoop Image AI.
          </p>
        </div>
        
        <div className="max-w-4xl mx-auto glass rounded-xl p-8 border border-white/10 relative">
          <div className="absolute top-6 right-6">
            <AlertTriangle className="w-8 h-8 text-amber-400" />
          </div>
          
          <h3 className="text-xl font-bold mb-4 text-white">Disclaimer of Liability</h3>
          
          <div className="space-y-4 text-gray-300">
            <p>
              Snoop Image AI is provided as an experimental research tool for informational purposes only. 
              While we strive for accuracy, the technology for detecting AI-generated images is still evolving,
              and the results provided by our tool should not be considered definitive or legally binding.
            </p>
            
            <p>
              The analysis, assessments, and probability scores generated by Snoop Image AI are based on algorithmic 
              pattern recognition and are intended as guidance only. Our tool can and will sometimes produce incorrect 
              results, false positives, or false negatives.
            </p>
            
            <p>
              By using Snoop Image AI, you acknowledge and agree that:
            </p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>The results provided are not guaranteed to be accurate or complete</li>
              <li>You will not rely solely on our tool for critical decisions</li>
              <li>We are not responsible for any actions taken based on the results provided</li>
              <li>The tool is provided "as is" without warranties of any kind</li>
              <li>We are not liable for any damages arising from the use of our tool</li>
            </ul>
            
            <p>
              AI Web Tools LLC, its affiliates, partners, and employees disclaim all liability for any loss, damage, 
              or costs that may result from the use of Snoop Image AI or reliance upon its results.
            </p>
            
            <div className="flex items-start gap-3 mt-6 p-4 rounded-lg bg-white/5">
              <Info className="w-5 h-5 text-neon-blue shrink-0 mt-1" />
              <p className="text-sm">
                This tool should be used as one of multiple sources when evaluating image authenticity. 
                For legal or high-stakes verification, we recommend consulting with professional forensic experts.
              </p>
            </div>
          </div>
        </div>
        
        <div className="mt-12 text-center">
          <p className="text-gray-400">By using Snoop Image AI, you agree to these terms.</p>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
